title: "MMT"
tagline: "Mobile Mapping for Autonomous Systems and Spatial Intelligence"

# url: https://3dvconf.github.io   ########
url: https://mmt2025.xmu.edu.cn
baseurl: "https://mmt2025.xmu.edu.cn"

# twitter: https://twitter.com/3DVconf
# xiaohongshu: https://www.xiaohongshu.com/user/profile/6360cac9000000001f018c8c

permalink: /:categories/:title/
safe: true
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown

kramdown:
    smart_quotes:  ["apos", "apos", "ldquo", "rdquo"]

encoding: utf-8

plugins:
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
    - jekyll-redirect-from

# Use this for production
sass:
    style: compressed
exclude: [.scss, README.md, node_modules, gruntfile.js, package.json, assets/]


collections:
  papers:
    output: true
    permalink: /:collection/:name

    
future: true
